log:
  level: debug
debug:
  port: 6060
http:
  port: 5002
  address: 0.0.0.0
  publicURL: http://127.0.0.1:5002
admin:
  port: 5301
  address: 0.0.0.0
  publicURL: http://127.0.0.1:5301
  enabled: true
spi:
  port: 5301
  address: 0.0.0.0
  publicURL: http://127.0.0.1:5301
  enabled: true
metrics: {}
ui:
  path: ./frontend
node:
  name: node_2f11c2
event:
  dbevents:
    bufferSize: 10000
plugins:
  database:
  - name: database0
    type: sqlite3
    sqlite3:
      url: /etc/firefly/db?_busy_timeout=5000
      migrations:
        auto: true
  blockchain:
  - name: blockchain0
    type: fabric
    fabric:
      fabconnect:
        url: http://fabconnect_2:3000
        channel: firefly
        chaincode: firefly
        topic: "2"
        signer: org_2f11c2
  sharedstorage:
  - name: sharedstorage0
    type: ipfs
    ipfs:
      api:
        url: http://ipfs_2:5001
      gateway:
        url: http://ipfs_2:8080
  dataexchange:
  - name: dataexchange0
    type: ffdx
    ffdx:
      url: http://dataexchange_2:3000
namespaces: null
